export const collections = [
  "Prison Break",
  "Bank Heist",
  "Mobile Escape Room",
  "Murder Mystery Party",
  "Standard Team Building",
  "Premium Team Building",
  "Team Olympics",
  "Adventure Quest",
  "Corporate Gaming League",
  "Employee Onboarding Pack",
  "The Big Picture",
  "Conference Ice Breakers",
  "Training Games",
  "Knowledge Bank",
  "Diversity, Equity & Inclusion",
  "Safety First",
  "Thank You Experience",
  " Games Night",
  "Party Fun Experience",
  "Mix and Match Experience",
  "Add On Experiences",
  "The Dash-Hunt : The (Name of Company) Edition",
  "The Pub Explorer & Lounge Experience",
];
